#CONTACT
soleil_contact_accueil:
    pattern:  /contact
    defaults: { _controller: soleilContactBundle:Contact:index }
    
#ADMINISTRATION

soleil_contact_accueil_admin:
  pattern : /admin/contact
  defaults: { _controller: soleilContactBundle:Contact:contact }
  
soleil_contact_voir_admin:
  pattern : /admin/contact/{slug}/voir
  defaults: { _controller: soleilContactBundle:Contact:voir }
  
soleil_contact_ajouter_admin:
  pattern : /admin/contact/ajouter
  defaults: { _controller: soleilContactBundle:Contact:ajouter }
  
########
soleil_contact_modifier_admin:
  pattern : /admin/contact/{slug}/modifier
  defaults: { _controller: soleilContactBundle:Contact:modifier }
  
soleil_contact_supprimer_admin:
  pattern : /admin/contact/{slug}/supprimer
  defaults: { _controller: soleilContactBundle:Contact:supprimer }
