parameters:
#    soleil_contact.example.class: soleil\ContactBundle\Example

services:
#    soleil_contact.example:
#        class: %soleil_contact.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
