<?php

namespace soleil\FormationBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class FormationController__JMSInjector
{
    public static function inject($container) {
        $instance = new \soleil\FormationBundle\Controller\FormationController();
        return $instance;
    }
}
