<?php

namespace soleil\ContactBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ContactController__JMSInjector
{
    public static function inject($container) {
        $instance = new \soleil\ContactBundle\Controller\ContactController();
        return $instance;
    }
}
