<?php

namespace soleil\ecommerceBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CommandeController__JMSInjector
{
    public static function inject($container) {
        $instance = new \soleil\ecommerceBundle\Controller\CommandeController();
        return $instance;
    }
}
