<?php

namespace soleil\SiteBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \soleil\SiteBundle\Controller\AdminController();
        return $instance;
    }
}
