<?php

namespace soleil\DonBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DonController__JMSInjector
{
    public static function inject($container) {
        $instance = new \soleil\DonBundle\Controller\DonController();
        return $instance;
    }
}
