soleil_realisation_accueil:
    pattern:  /realisation
    defaults: { _controller: soleilecommerceBundle:Realisation:index }
    
#PAIEMENT
    
soleil_realisation_paiement_details:
    pattern:  /realisation/achat/paiement/details/transaction/{slug_r}
    defaults: { _controller: soleilecommerceBundle:Payement:details }

soleil_realisation_paiement_cancel:
    pattern:  /realisation/achat/paiement/cancel
    defaults: { _controller: soleilecommerceBundle:Payement:cancel }
    
soleil_realisation_paiement_return:
    pattern:  /realisation/achat/paiement/return
    defaults: { _controller: soleilecommerceBundle:Payement:return }

#ADMINISTRATION

soleil_realisation_accueil_admin:
  pattern : /admin/realisation
  defaults: { _controller: soleilecommerceBundle:Realisation:realisation }
 
soleil_realisation_voir_admin:
  pattern : /admin/realisation/{slug}/voir
  defaults: { _controller: soleilecommerceBundle:Realisation:voir }
  
soleil_realisation_ajouter_admin:
  pattern : /admin/realisation/ajouter
  defaults: { _controller: soleilecommerceBundle:Realisation:ajouter }
  
soleil_realisation_modifier_admin:
  pattern : /admin/realisation/{slug}/modifier
  defaults: { _controller: soleilecommerceBundle:Realisation:modifier }
  
soleil_realisation_supprimer_admin:
  pattern : /admin/realisation/{slug}/supprimer
  defaults: { _controller: soleilecommerceBundle:Realisation:supprimer }
  
  #COMMANDE
  
soleil_commande_accueil_admin:
  pattern : /admin/commande
  defaults: { _controller: soleilecommerceBundle:Commande:index }
  
soleil_commande_voir_admin:
  pattern : /admin/commande/voir/{slug}
  defaults: { _controller: soleilecommerceBundle:Commande:voir }
  
soleil_commande_supprimer_admin:
  pattern : /admin/commande/supprimer/{slug}
  defaults: { _controller: soleilecommerceBundle:Commande:supprimer }