<?php

namespace soleil\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RubriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RubriqueRepository extends EntityRepository
{
    public function getDescription(){
            
        $domaine = $_SERVER['HTTP_HOST'];
            
            $qb = $this->createQueryBuilder('r'); 
                $qb->join('r.sites', 's'); 
                
                //$qb->addSelect('r');               
                //$qb->andwhere('s.domaine = :dom');
                //$qb->setParameter('dom', $domaine);
                $qb->where('r.id = 6');
                

            return $qb->getQuery()->getSingleResult();
            
    }
}
