<?php

namespace soleil\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Symfony\Component\HttpFoundation\Session\Session;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteRepository extends EntityRepository
{
    
    public function getSiteParHost(){
        
        $domaine = $_SERVER['HTTP_HOST'];
            
            $qb = $this->createQueryBuilder('s'); 

                $qb->where('s.domaine = :dom');
                $qb->setParameter('dom', $domaine);

            return $qb->getQuery()->getSingleResult();
            
    }
    
    public function getmenuSousSite(){
            
            $domaine = $_SERVER['HTTP_HOST'];
            
            $qb = $this->createQueryBuilder('s'); 
                $qb->join('s.rubriques', 'r'); 
                $qb->addSelect('r');
                
                
                    $qb->where('r.menusite = 1');
                
                
                $qb->andwhere('s.domaine = :dom');
                $qb->setParameter('dom', $domaine);
                
                

            return $qb->getQuery()->getResult();
        }
        
        public function getmenuSousSiteAdmin(){
            
            $domaine = $_SERVER['HTTP_HOST'];
            
            $qb = $this->createQueryBuilder('s'); 
                $qb->join('s.rubriques', 'r'); 
                
                $qb->addSelect('r');               
                $qb->andwhere('s.domaine = :dom');
                $qb->setParameter('dom', $domaine);

            return $qb->getQuery()->getResult();
        }
        
        /*
         $qb->setFirstResult(0);
                $qb->setMaxResults(2);
         */
        public function menuChangerSiteAction(){
            $qb = $this->createQueryBuilder('s');
            $qb->setFirstResult(0);
                $qb->setMaxResults(3);
                
                return $qb->getQuery()->getResult();
        }
}
