parameters:
#    soleil_user.example.class: soleil\UserBundle\Example

services:
#    soleil_user.example:
#        class: %soleil_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
