#=> accueil == render


#ADMINISTRATION

soleil_formation_accueil_admin:
    pattern:  /admin/formation
    defaults: { _controller: soleilFormationBundle:Formation:formation }
    
soleil_formation_voir_admin:
    pattern:  /admin/formation/{slug}/voir
    defaults: { _controller: soleilFormationBundle:Formation:voir }
    options:
        expose: true
    
soleil_formation_ajouter_admin:
    pattern:  /admin/formation/ajouter
    defaults: { _controller: soleilFormationBundle:Formation:ajouter }
    
soleil_formation_modifier_admin:
    pattern:  /admin/formation/{slug}/modifier
    defaults: { _controller: soleilFormationBundle:Formation:modifier }
    
soleil_formation_supprimer_admin:
    pattern:  /admin/formation/{slug}/supprimer
    defaults: { _controller: soleilFormationBundle:Formation:supprimer }
