<?php

namespace soleil\AgendaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EvenementAgendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementAgendaRepository extends EntityRepository
{
    public function getEvenementParSite(){
        
        $domaine = $_SERVER['HTTP_HOST'];
            
            $qb = $this->createQueryBuilder('ea'); 
                $qb->Select('ea.id','ea.nomFr','ea.nomEn','ea.slug','ea.dateDeb','ea.dateFin','ea.nbMax','ea.nbInsc','f.titreFr', 'f.slug AS fslug'); 
                $qb->join('ea.site', 's');
                $qb->join('ea.formation','f');
                
                $qb->where('s.domaine = :dom');
                $qb->setParameter('dom', $domaine);

            return $qb->getQuery()->getArrayResult();
            
    }
    
    public function getEvenementParSiteAvecInscri(){
        
        $domaine = $_SERVER['HTTP_HOST'];
        
        $qb = $this->createQueryBuilder('ev');
        
        $qb ->join('ev.site', 's');
        $qb ->join('ev.inscris', 'i'); 
        
        $qb->addSelect('i');

        $qb->where('s.domaine = :dom');
        $qb->setParameter('dom', $domaine);
        
        //$qb->orderBy('i.dateIns', 'DESC');
        $qb->orderBy('ev.dateDeb', 'ASC');
        $qb->addOrderBy('i.dateIns', 'DESC');

        return $qb->getQuery()->getResult();
        
    }
    

    
}
