<?php

namespace soleil\AgendaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InscriRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriRepository extends EntityRepository
{
    
}
