parameters:
#    soleil_don.example.class: soleil\DonBundle\Example

services:
#    soleil_don.example:
#        class: %soleil_don.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
