<?php

namespace soleil\ecommerceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
    public function getCommande(){
        
        $qb = $this->createQueryBuilder('c');
        
        //$qb->orderBy('i.dateIns', 'DESC');
        $qb->addOrderBy('c.dateIns', 'DESC');

        return $qb->getQuery()->getResult();
        
    }
}
