#ARTICLE
soleil_article_accueil:
  pattern : /article
  defaults: { _controller: soleilArticleBundle:Article:liste }
  
soleil_article_voir_plus:
  pattern : /article/{voirplus}
  defaults: { _controller: soleilArticleBundle:Article:voirplus }

#ADMINISTRATION

soleil_article_accueil_admin:
  pattern : /admin/article
  defaults: { _controller: soleilArticleBundle:Article:article }
  
soleil_article_voir_admin:
  pattern : /admin/article/{slug}/voir
  defaults: { _controller: soleilArticleBundle:Article:voir }
  
soleil_article_ajouter_admin:
  pattern : /admin/article/ajouter
  defaults: { _controller: soleilArticleBundle:Article:ajouter }
  
soleil_article_modifier_admin:
  pattern : /admin/article/{slug}/modifier
  defaults: { _controller: soleilArticleBundle:Article:modifier }
  
soleil_article_supprimer_admin:
  pattern : /admin/article/{slug}/supprimer
  defaults: { _controller: soleilArticleBundle:Article:supprimer }